package:
  name: r-DeepESD
  version: 0.0.0
build:
  string: r36_1
  noarch: generic
requirements:
  build: []
  run:
  #r dependencies
  - r-base >=3.6.1,<3.7
  - r-climate4r.udg ==0.2.2
  - r-loader.java ==1.1.1
  - r-loader ==1.7.0
  - r-loader.2nc ==0.1.1
  - r-loader.ecoms ==1.4.6
  - r-transformer ==2.1.0
  - r-downscaler ==3.3.2
  - r-downscaler.keras ==1.0.0
  - r-visualizer ==1.6.0
  - r-convertr ==0.2.0
  - r-climate4r.indices ==0.2.0
  - r-value ==2.2.2
  - r-climate4r.value ==0.0.2
  - r-climate4r.datasets ==0.0.1
  #python dependencies
  - python >=3.6,<3.8
  - iris ==3.0.4 

about:
  home: http://www.meteo.unican.es/2022_Bano_DeepESD_GMD
  license: GPL-3.0-or-later
  summary: R environment to reproduce the manuscript 'Downscaling Multi-Model Climate Projection Ensembles with Deep Learning (DeepESD): Contribution to CORDEX EUR-44'
  license_family: GPL3

extra:
  recipe-maintainers:
    - conda-forge/r
    - bmedina
