name: deepesd-test
channels:
  - conda-forge
#  - r
#  - defaults
#  - santandermetgroup
#  - conda-forge/label/broken
  - nodefaults
dependencies:
  #r dependencies
  - r-base             >=3.6.1,<4
  - r-loader           ==1.7.0
  - r-loader.2nc       ==0.1.1
  - r-transformer      ==2.1.0
  - r-downscaler       ==3.3.2
  - r-visualizer       ==1.6.0
  - r-downscaler.keras ==1.0.0
  - r-climate4r.value  ==0.0.2
  - r-climate4r.udg    ==0.2.2
  # 
  - r-value            ==2.2.2
  - r-loader.java      ==1.1.1
  #python dependencies
  - python <3.10
  ## Jupyter and JupyterHub dependencies
  - r-irkernel
  - jupyter
  - jupyterhub
  - notebook
  - jupyterlab
  - jupyter_nbextensions_configurator 
  - nbgitpuller # required to decouple binder and repo
  - jupyter-resource-usage
  - jupyter_contrib_nbextensions
  ## Dependencies for notebooks
  - r-devtools     
  - r-magrittr     
  - r-rcolorbrewer 
  - r-gridextra    
  - r-ggplot2      
  ## other tools dependencies
  - cdo >=1.9,<2.0
  
  
  

